107-server-buttons
dzmipt/kdbStudio pull request #108
Opened 2021-09-30 23:30 UTC by Yanpas

The icons are taken from KDE project (Breeze theme)

2021-10-05 21:13 UTC, dzmipt commented on src/studio/ui/ServerList.java
> +    private static final int menuShortcutKeyMask = java.awt.Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx();
This one is not compilable with Java 8

2021-10-06 09:08 UTC, Yanpas commented
- [ ] make buttons active/inactive depending on server history

2021-10-08 21:18 UTC, dzmipt requested changes

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +        nextServerAction.setEnabled(serverNavigateHistory.hasNextItem());
And below (hidden in the review) is the reason I don't like the concept of NavigationHistory (which I already advertised earlier). We simply already have serverHistory. I think we need one navigation or serverHistory. The logic should be combined.

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +        prevServerAction.setEnabled(serverNavigateHistory.hasPreviousItem());
I want to put logic for actions enable/disable into a single place - refreshActionState()

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +        prevServerAction.setEnabled(false);
I'd like to put all action.setEnabled into refreshActionState()

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +        prevServerAction = UserAction.create("Previous server", Util.BACK_ICON, "Previous server", 0,
I would like to have some shortcuts (didn't come up what exact shortcut)

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +        nextServerAction.setEnabled(serverNavigateHistory.hasNextItem());
... and serverHistoryAction should move a selectedIndex pointer in the navigationHistory, rather than adding an item in the end of the navigation

2021-10-08 21:18 UTC, dzmipt commented on src/studio/ui/StudioPanel.java
> +    private void setServer(Server server, boolean addToNavigationHistory) {
Here is what I spot but think a lot how I would do it here.. 
I don't like the boolean addToNavigationHistory argument. As we have different use-cases - replace the current item, add to the tail, move back and forward.
May be we need to have setServer(server) meaning we have a new Server which we want to set and add to the tail; and a separate method navigate(boolean moveForward) which is used for navigation?

2023-07-19 11:19 UTC, closed without merging